#!/bin/bash
log_file="/opt/planka/logs/cron.log"

DOWNLOAD_URL_INSTALLER_FILE="https://raw.githubusercontent.com/plankanban/planka-installer/main/installer.sh"
DOWNLOAD_URL_PATCH_CRON_SCRIPT_FILE="https://raw.githubusercontent.com/plankanban/planka-installer/main/cron/patch.sh"
DOWNLOAD_URL_CRON_FILE="https://raw.githubusercontent.com/plankanban/planka-installer/main/cron/planka-cron"

echo "$(date +'%d.%m.%y - %H:%M') - Starting Daily cron..." >> "$log_file" 2>&1
echo "$(date +'%d.%m.%y - %H:%M') - Downloading files..." >> "$log_file" 2>&1

curl -fsSL $DOWNLOAD_URL_CRON_FILE -o /etc/cron.daily/planka-cron;
curl -fsSL $DOWNLOAD_URL_INSTALLER_FILE -o /opt/planka_installer.sh;
curl -fsSL $DOWNLOAD_URL_PATCH_CRON_SCRIPT_FILE -o /opt/planka/cron/patch.sh;

echo "$(date +'%d.%m.%y - %H:%M') - Setting permissions...." >> "$log_file" 2>&1
chmod +x /opt/planka/cron/*.sh >> "$log_file" 2>&1

echo "$(date +'%d.%m.%y - %H:%M') - Executing tasks..." >> "$log_file" 2>&1

echo "$(date +'%d.%m.%y - %H:%M') - Patching Planka installer scripts..." >> "$log_file" 2>&1
/opt/planka/cron/patch.sh >> "$log_file" 2>&1

echo "$(date +'%d.%m.%y - %H:%M') - Backing up Planka..." >> "$log_file" 2>&1
/opt/planka/cron/backup.sh >> "$log_file" 2>&1

echo "$(date +'%d.%m.%y - %H:%M') - Updating Planka..." >> "$log_file" 2>&1
/opt/planka/cron/planka_update.sh >> "$log_file" 2>&1


echo "$(date +'%d.%m.%y - %H:%M') - Cleanup cron.log file..." >> "$log_file" 2>&1
echo "$(tail -1000 $log_file)" > "$log_file"

echo "$(date +'%d.%m.%y - %H:%M') - Daily cron done..." >> "$log_file" 2>&1